service:
  name: coa
  
custom:
  localstack:
    stages:
      - local
    host: http://localhost  # optional - LocalStack host to connect to
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  
plugins:
  - serverless-webpack
  - serverless-localstack
  
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  # environment:
    # AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  auth:
    handler: src/drivers/jwt/tokenManager.handler
  coa:
    handler: src/handler.changeObjectAuthorHandler
    events:
      - http: post test
        cors: true
        authorizer: auth