org: eolani1
app: coa-app
service:
  name: coa
  
custom:
  localstack:
    stages: [local]
    autostart: true
    lambda:
      mountCode: true

  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  
plugins:
  - serverless-webpack
  - serverless-localstack
  - serverless-plugin-simulate
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  # environment:
    # AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  auth:
    handler: src/drivers/jwt/tokenManager.handler
  coa:
    handler: src/handler.changeObjectAuthorHandler
    events:
      - http:
          path: src/handler.changeObjectAuthorHandler
          method: post
          cors: true
          authorizer: auth
          headers: 
            - Content-Type
            - x-Amz-Date
            - Authorization
            - X-Api-key
            - X-Amz-Security-Token