org: eolani1
app: coa-app
service:
  name: coa

custom:
  serverless-offline:
    httpPort: 5001
    region: us-east-1
    stage: dev
  
plugins:
  - serverless-webpack
  - serverless-plugin-simulate
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account.
  - Effect: "Allow"
    Action:
      - "*"
    Resource:
      - arn:aws:s3:::*

functions:
  auth:
    handler: src/drivers/jwt/tokenManager.handler
  coa:
    handler: src/handler.changeObjectAuthorHandler
    events:
      - http:
          path: /changeObjectAuthorHandler
          method: post
          cors: true
          authorizer: auth
          headers: 
            - Content-Type
            - x-Amz-Date
            - Authorization
            - X-Api-key
            - X-Amz-Security-Token
            