service:
    name: change-object-author
  
  custom:
    webpack:
      webpackConfig: ./webpack.config.js
      includeModules: true
  
  # Add the serverless-webpack plugin
  plugins:
    - serverless-webpack
  
  provider:
    name: aws
    runtime: nodejs10.x
    apiGateway:
      minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  
  functions:
    outage-download-test:
      handler: src/handler.changeObjectAuthorHandler
      events:
        - http: POST changeObjectAuthorHandler